### ISSUE TITLE
Exclude URI path from access_log

### ISSUE THREAD

**Issue by iexplore** [wodby/nginx#10]
Type: enhancement
Environment: Kubernetes

We are using the Drupal 8 health_check module for K8 readiness and liveness tests but this clutters the access log. 
Is het possible to create a variabele to exclude a path from the access_log (/health in our case)?

Ref: https://www.drupal.org/project/health_check

**Comment by csandanov** [comment]
We already have `/.healthz` endpoint for that and a check ready orchestration action https://github.com/wodby/nginx/blob/master/bin/actions.mk#L14

**Comment by iexplore** [comment]
Yes, this is great. We are already using this for our frontend, but this is a health check for nginx, it doesn't do a Drupal bootstrap,  access the database etc.

**Comment by csandanov** [comment]
You can use `$NGINX_SERVER_EXTRA_CONF_FILEPATH` to add a location to exclude from access logs [as we do it for `/.heathlz`](https://github.com/wodby/nginx/blob/master/templates/includes/defaults.conf.tmpl#L61)
