### ISSUE TITLE
Multiple index files in NGINX_INDEX_FILE cause Nginx container startup error

### ISSUE THREAD

**Issue by PavelPrischepa** [wodby/nginx#11]
Specifying multiple values (index files) in `NGINX_INDEX_FILE` cause Nginx container startup error:
```
nginx: [emerg] invalid number of arguments in "fastcgi_index" directive in /etc/nginx/fastcgi.conf:36
```
It seems it is here https://github.com/wodby/nginx/blob/master/templates/includes/fastcgi.conf.tmpl#L36.

Docker image: `wodby/nginx:1.15-5.0.16`
Preset: `WordPress`
NGINX_INDEX_FILE value: `index.php index.html`

**Comment by csandanov** [comment]
We should add index.html by default to wp, drupal, php presets for decoupled frontend cases. And add another env var for fastcgi index file since it may have only single `*.php` value
