### ISSUE TITLE
Making www-data user id customizable?

### ISSUE THREAD

**Issue by lukasz-zaroda** [wodby/nginx#2]
Just a question: would it be maybe possible to make user id of www-data user customizable by environmental variable?

Currently when I'm running drupal-nginx container, the owner of the volume directory becomes user 82, which makes problems. Maybe customizable user id of www-data could solve the problem, by making it possible to set www-data user to the same id as the user on the host? Is it even possible? Or maybe there is some other way to get around of this? I'm kind of new so maybe I missed something.

**Comment by csandanov** [comment]
There's no way to customize it via environment variable because it's set in Dockerfile. To fix permissions problem follow [these instructions](http://docs.docker4drupal.org/en/latest/permissions/)

**Comment by lukasz-zaroda** [comment]
Wouldn't this work? http://stackoverflow.com/questions/34322631/how-to-pass-arguments-within-docker-compose, it seems to be already possible to pass variables to docker-compose.yml .

**Comment by csandanov** [comment]
Why not just create a group on your host machine with ID 82 as described [here](http://docs.docker4drupal.org/en/latest/permissions/)?

**Comment by lukasz-zaroda** [comment]
It works and I'm using it right now, but it doesn't feel "right". Maybe we could achieve the same without mixed owners - that's what I'm suggesting, but I'm not sure if it's a good solution, just a suggestion.

**Comment by csandanov** [comment]
The ID 82 is a standard gid/uid for www-data in alpine linux and since you're using nginx with php, the user should be the same in both containers, see [Dockerfile](https://github.com/docker-library/php/blob/ec02e1bcf1196ed3f8b74ecc956cf81554e32db8/7.1/fpm/alpine/Dockerfile) of the official php-fpm image that we use for drupal-php (82 uid/gid is used).

**Comment by lukasz-zaroda** [comment]
I'm using Arch Linux and I don't even have "www-data" user. Arch Linux have an "http" user with id 33. That's why I was looking for a more flexible solution.

**Comment by PavelPrischepa** [comment]
@lukasz-zaroda you can add `alpine-www-data` or `alpine-http` group. Or you can override d4d containers via docker-compose [build](https://docs.docker.com/compose/compose-file/#build). An issue-related [comment](https://github.com/wodby/docker4drupal/issues/64#issuecomment-265067514) in other thread.
