### ISSUE TITLE
Change the default value of ssl_session_cache?

### ISSUE THREAD

**Issue by HCHCHH** [wodby/nginx#28]
The Nginx [official document](http://nginx.org/en/docs/http/ngx_http_ssl_module.html) recommends to enable **ssl_session_cache** and set that to **shared:name:size**, which enables cache shared between all worker processes.

"To reduce the processor load it is recommended to set the number of worker processes equal to the number of processors, enable keep-alive connections,**enable the shared session cache**,"

I wonder whether the default setting need to be changed.  Thanks.

**Comment by csandanov** [comment]
Currently, the way this image designed is to be used behind a reverse proxy that terminates SSL (nginx ingress, traefik) so I don't think it makes sense to add configurability for those params.
