### ISSUE TITLE
Query parameters are not being passed to the script

### ISSUE THREAD

**Issue by lukasz-zaroda** [wodby/nginx#3]
Is there any reason why in fastcgi_params.tpl there is no `fastcgi_param QUERY_STRING $query_string;` line? I just finished a long debugging session to conclude that query parameters are not being passed to the web server, because of lack of this line, and this breaks some ready nginx configurations available on the internet. As you can see, in nginx this parameter is set by default: https://github.com/nginx/nginx/blob/branches/stable-1.10/conf/fastcgi_params

**Comment by csandanov** [comment]
We use this image as a base for https://github.com/wodby/drupal-nginx and https://github.com/wodby/wordpress-nginx, and both them [have this param](https://github.com/wodby/drupal-nginx/blob/master/8/1.10/drupal.conf.tpl). Are you using this image directly? Perhaps we can add this line.

**Comment by lukasz-zaroda** [comment]
Yes, I was trying to make a Prestashop nginx image based on `wodby/nginx`, and it caused very strange behavior (front end worked just fine, but back office was giving a redirection loop). I think this line should be added if it wasn't consciously removed. :)

**Comment by csandanov** [comment]
The param has been added.
