### ISSUE TITLE
Nginx Drupal 8 preset is not compatible with robotstxt module

### ISSUE THREAD

**Issue by iVegas** [wodby/nginx#43]
Steps to reproduce:
- Up and running Docker4Drupal stack;
- Installed the latest version of Drupal 8.
- removed `web/robots.txt` file;
- enabled `robotstxt` module on Drupal 8 installation;
- go to the `/robots.txt` page;

Expected results:
- Status code - `200`;
- Returned default content of `robots.txt` file provided by `robotstxt` module;

Actual result:
- Status code - `404`;
- No result provided. No request redirected to index.php when `robots.txt` file not exists.

**Comment by snowtorious** [comment]
It looks like support for dynamically generated robots.txt file was added with this commit: https://github.com/wodby/nginx/commit/81e32d1ce317b635bc902253b5a026138fb38329

Adding the following to a custom site.conf.tmpl file allows Drupal to serve a dynamic robots.txt file:
```
location = /robots.txt {
    try_files $uri @drupal;
}
```

Note that this issue also affects the Drupal 7 preset.

**Comment by iVegas** [comment]
The maintainer added support for the WordPress template. Drupal templates (supported versions) need the same configuration.

**Comment by csandanov** [comment]
Added robots.txt support
