### ISSUE TITLE
Custom presets

### ISSUE THREAD

**Issue by ventzie555** [wodby/nginx#50]
Custom presets will not work. Look at the docker-entrypoint.sh:
if [[ "${NGINX_VHOST_PRESET}" =~ ^drupal8|drupal7|drupal6|wordpress|php$ ]]; then
            _gotpl "includes/upstream.php.conf.tmpl" "/etc/nginx/upstream.conf"
        elif [[ "${NGINX_VHOST_PRESET}" =~ ^http-proxy|django$ ]]; then
            if [[ -z "${NGINX_BACKEND_HOST}" && "${NGINX_VHOST_PRESET}" == "django" ]]; then
                export NGINX_BACKEND_HOST="python";
            fi

            _gotpl "includes/upstream.http-proxy.conf.tmpl" "/etc/nginx/upstream.conf"
        fi

As you see upstream is not gonna be parsed for custom preset and an error is generated:
**_nginx: [emerg] no port in upstream "php" in_**

**Comment by csandanov** [comment]
Thank you. Now it will look for a `/etc/gotpl/includes/upstream.[preset].conf.tmpl`, if it doesn't exists it will create an empty upstream file.
