### ISSUE TITLE
Are AdvAgg rules working?

### ISSUE THREAD

**Issue by proteo** [wodby/nginx#51]
Hi there. I'm using the AdvAgg module and everything is working great except one small thing. Im using the [D7 configuration](https://github.com/wodby/nginx/blob/master/templates/presets/drupal7.conf.tmpl) but for some reason the location directive in line #55 is not working:

```
location ~* /sites/.*/files/advagg_css/css[_[:alnum:]]+\.css$ {
    access_log {{ getenv "NGINX_STATIC_ACCESS_LOG" "off" }};
    try_files $uri @drupal;
}
```

For one, I've disabled the static access log so AdvAgg files shouldn't be logged but they are. Also, I'm trying to send the inmutable cache-control directive in the same block, like this, but it's being ignored:

```
location ~* /sites/.*/files/advagg_css/css[_[:alnum:]]+\.css$ {
    access_log {{ getenv "NGINX_STATIC_ACCESS_LOG" "off" }};
    add_header Cache-Control "public, max-age=31536000, no-transform, immutable";
    try_files $uri @drupal;
}
```
If I put the directive in the outer block it works just fine. The issue seems to be the regex used to match the naming of AdvAgg's generated files. At least in the latest version (7.x-2.34) for Drupal 7, files are named something like this:

`/sites/default/files/advagg_css/css__Tdw-8Mmgx7YtZQ05A9emTDXqrePB-bcUuv-axU4dEPc__ojEG3uFjJdKmsUekgDv2pRvliB8cz3RA2wwjKCXw8KA__0DJ0ZG79NTA--zXyGIopzC36trgu9i59TXgnuPuToaE.css`

I'm not an expert but it looks like the `css[_[:alnum:]]+\.css` expression is trying to match a string like css_0123456789.css (obviously it may contain many more numbers) but in any case it won't be able to match anything given the current naming convention.

Should I just drop these lines in the outer block?

Thanks a lot in advance!

**Comment by proteo** [comment]
Something like this seems to do the job in my informal tests. Any reason not to use it?

`location ~* /sites/.*/files/advagg_css/css_[a-z0-9_-]+\.css$`

**Comment by csandanov** [comment]
Thank for reporting this. Regex are now fixed, also added cache-control headers

**Comment by proteo** [comment]
Thanks!
