### ISSUE TITLE
Using container standalone isseu

### ISSUE THREAD

**Issue by nickvanboven** [wodby/nginx#52]
I am trying to use this container in a working project, the website loads but assets arend loaded en get a 404 from drupal. I am sharing only the files dir on a volume to nginx. Is there a way to get nginx to load js and css from core modules through the webserver? At the moment it tries to send it to index.php which result in a 404

**Comment by esolitos** [comment]
You need to mount also the drupal codebase to nginx container, or else it will not have accessto all the JS/CSS/.. from drual, only to the public files, as you indicated.
I suggest looking at [docker4drupal's docker-compose.yml](https://github.com/wodby/docker4drupal/blob/master/docker-compose.yml#L17-L46) where you can see it in action/.
