### ISSUE TITLE
change root path

### ISSUE THREAD

**Issue by killfill** [wodby/nginx#6]
Hello,

Lets say we have a php project in the directory located at /var/www/html/my-project 
When trying to define that as the root dir of nginx, something seems to be failing:

https://github.com/wodby/nginx/blob/master/templates/includes/defaults.conf.tmpl#L7-L9

It looks like nginx will respond with some happy's 302 all the time, probably that sentence does not know the root it in that special directory. (this is a wordpress site, with the 'wordpress' preset been used)

What can we do about this?

It looks like nginx does not allow to put 'root /var/www/html/my-project ' in that particular sentence.

Thanks!

**Comment by csandanov** [comment]
Did you set `NGINX_SERVER_ROOT` to `/var/www/html/my-project`? Please share more, nginx env vars and curl output.
