### ISSUE TITLE
Overriding log format

### ISSUE THREAD

**Issue by mralexho** [wodby/nginx#7]
I'm having some trouble overriding **log_format**.

I added the **NGINX_LOG_FORMAT_OVERRIDE** variable with the following string:

`$http_x_forwarded_for - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent"`

When I redeploy my stack, I receive the error:

`nginx: [emerg] duplicate "log_format" name "combined" in /etc/nginx/nginx.conf:20`

My stack is running the **wodby/drupal-nginx:7-1.15-4.2.0** image.

**Comment by csandanov** [comment]
Thank you for reporting this issue, it's fixed now and available in `-5.0.1` stabiltiy tag, image `wodby/drupal-nginx` no longer supported, instead use `wodby/nginx` (`wodby/nginx:1.15-5.0.1` in your case) with the environment variable `NGINX_VHOST_PRESET=drupal7`
