### ISSUE TITLE
Allow .yml in files directory (just like .txt)

### ISSUE THREAD

**Issue by ChristophWeber** [wodby/nginx#75]
YAML files are often attached to content for explanatory or documentation purposes. A blanket ban makes no sense, and .yaml is still allowed sitewide anyway.
A concrete example of uploaded .yml files is in a developer portal, where a valid OpenAPI specification can be in JSON or YAML format, and needs to be uploaded for later rendering via SwaggerUI or a similar library. There are certainly other use cases that are all completely valid. YAML or JSON files in the files directory are safe because of all the other precautions we have in the config. I realize that the blanket 404 is a straight port from Drupal's .htaccess, and it should be fixed there as well, but here we can start.

Proposed change to line 39 of templates/presets/drupal9.conf.tmpl (and earlier Drupal versions as well):
 ```
-   location ~* /sites/.+/files/.+\.txt {
+   location ~* /sites/.+/files/.+\.(txt|yml) {
```

**Comment by csandanov** [comment]
Added `$NGINX_DRUPAL_FILES_STATIC_EXT_REGEX`, now you can override the default `txt`.

> A blanket ban makes no sense, and .yaml is still allowed sitewide anyway.

added `.yaml` to the default value of `NGINX_DRUPAL_NOT_FOUND_REGEX`

**Comment by mxr576** [comment]
Related commit: https://github.com/wodby/nginx/commit/aeedab8fb6e4e65c2754681e83354afbb6401fb9
