### ISSUE TITLE
Drupal 10.1.0 CSS Aggregation updates.

### ISSUE THREAD

**Issue by devbranch-bit** [wodby/nginx#85]
Drupal has updated the CSS aggregation logic on the `10.1.0` version.

On my case the website styles has been gone after updating Drupal to `10.1.0`.

They suggest to update the nginx configuration like this:
```
# Before

# Passes style generation to PHP.
location ~ ^/sites/.*/files/styles/ {
  try_files $uri @rewrite;
}
```

```
# After

# Passes image style and asset generation to PHP.
location ~ ^/sites/.*/files/(css|js|styles)/ {
  try_files $uri @rewrite;
}
```

[Source](https://www.drupal.org/node/2888767#nginx-php-fpm)

**Comment by csandanov** [comment]
Covered in https://github.com/wodby/nginx/pull/84
