### ISSUE TITLE
need to quote regex in rewrite rules for NGINX_WP_GOOGLE_XML_SITEMAP

### ISSUE THREAD

**Issue by Kidun** [wodby/nginx#94]
the issue is related to commit [fba9729](https://github.com/wodby/nginx/commit/fba9729581782ec20d3a6feaecb67fbdca181965)
according to the [nginx documentation](http://nginx.org/en/docs/http/ngx_http_rewrite_module.html#rewrite) 

> if a regular expression includes the “}” or “;” characters, the whole expressions should be enclosed in single or double quotes. 

in current state it causes CrashLoopBackOff for nginx pods, when NGINX_WP_GOOGLE_XML_SITEMAP=1 with the following error in log:
nginx: [emerg] directive "rewrite" is not terminated by ";" in /etc/nginx/preset.conf:23

Proposed change: in the file /etc/gotpl/presets/wordpress.conf.tmpl put regex in double quotes:
```
rewrite "^/.*sitemap.*(?:\d{1,4}(?!-misc)|-misc)?\.xml$" "/index.php?xml_sitemap=params=$2" last;
rewrite "^/.*sitemap.*(?:\d{1,4}(?!-misc)|-misc)?\.xml\.gz$" "/index.php?xml_sitemap=params=$2;zip=true" last;
rewrite "^/.*sitemap.*(?:\d{1,4}(?!-misc)|-misc)?\.html$" "/index.php?xml_sitemap=params=$2;html=true" last;
rewrite "^/.*sitemap.*(?:\d{1,4}(?!-misc)|-misc)?\.html.gz$" "/index.php?xml_sitemap=params=$2;html=true;zip=true" last;
```
temporary workaround until it's fixed:
build a docker image with modified /etc/gotpl/presets/wordpress.conf.tmpl file

**Comment by csandanov** [comment]
Thank you!
