### ISSUE TITLE
nginx rule for Laravel livewire in Laravel template

### ISSUE THREAD

**Issue by afraazali** [wodby/nginx#96]
When using Laravel Livewire, there's a script that's added, which uses the route: `/livewire.js`. The current nginx configuration tries to serve this as a static asset, due to the `NGINX_STATIC_EXT_REGEX` variable.

The current workaround is to simply remove `js` from the `NGINX_STATIC_EXT_REGEX` variable. Another work around is to create your own preset.

Would it be possible to add the follow location directive to the laravel preset:

```
location = /livewire/livewire.js {
    expires off;
    try_files $uri $uri/ /index.php?$query_string;
}
```

**Comment by csandanov** [comment]
Added, could you please test once the built completed. If everything is ok I will release a tag

**Comment by afraazali** [comment]
Thank you @csandanov. I confirmed this is working for me. I appreciate the quick turnaround!
